### ISSUE TITLE
🎙 talk.js - February 2019 🎉

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#17]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/258532004/)
- [x] Date: 13th February (Wed)
- [x] Hosts: @timoxley @ongmin
- [x] Venue: Viki Rakuten

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 5min, 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [Engineers.SG](https://engineers.sg/)
- [x] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by aelbore** [comment]
Title of the Talk
Web Components that works everywhere

Talk description
Reusability is one of the problem solved by web components, you will able to reuse custom elements to any javascript library (angular, vue, react and ember). 
Having consistent component libraries has benefits to large companies and teams regardless of tech stack, it ensures consistent look and feel without having to recreate everything from scratch again. 

Presenter(s):
github: https://github.com/aelbore
twitter: @VirtualOverride

Presenter's bio:
Works as a frontend developer in the bank, active in the open source. 

Duration requested:
30min

**Comment by ongmin** [comment]
Hi @khangtoh sounds good! Lets plan for mid February (say 13th)? Looking to move our meetup to the earlier half of the month. Let me know how I can best reach you, or you can get me on twitter at the same handler.

**Comment by khangtoh** [comment]
@ongmin  awesome! you can reach me via email khang.toh@gmail.com

**Comment by Weiyuan-Lane** [comment]
**Title of your talk**
Soompi: 20 years, Now, and the Future

**Talk description**
Soompi has had its humble beginnings since 1999. Since then, its readership has increase manyfold. In recent years, Wordpress has been the primary stack in running the service. But even with the modernising of the site's themes, the technology behind the scenes has been the bottleneck in providing better performance and hence better user experience for end users. In this session, we aim to dive into how we rewrote the entire application into a Isomorphic and a Single Page Application using ReactJS and NodeJS+ExpressJS, deployed on AppEngine Flex, how that solved the problems we faced at scale, and performance optimisations that were made alongside this change. We will also look at the future improvements that can be made to further improve the service from the perspective of JS.

Presenter(s)
- https://github.com/ikawka
- https://github.com/weiyuan-lane

**Presenter's bio**
Amiel and Weiyuan are fun people working at Rakuten Viki (both are also Full Stack Engineers)

**Duration requested**
20 mins

**Comment by scboesch** [comment]
**Title of your talk**
From Game-based Learning to Game Creation

**Talk description**
Each year, we invite around a thousand students to begin or continue their coding journeys by encouraging them to play CodeCombat as part of the [Singapore National Coding Championships](https://medium.com/@scboesch/2017-singapore-national-coding-championships-recap-7a2fcce75dc1). We then invite around 10% of the students who participate online to join us for a live team-based coding competition. Some of the more adventurous students go on to create their own game levels for their friends and family to play. And while it is possible to play CodeCombat in multiple programming languages, the multiplayer levels that we play in national infocomm competition finals are written in Javascript. In this talk, I will provide a brief overview of the javascript skills that beginner students gain as they play online, the skills they need in the live, team-based finals, and the skills that are needed to transition from being a finals competitor to someone capable of creating the experiences that other students can play. 
 
**Presenter**
Chris Boesch - https://github.com/scboesch/

**Presenter's bio**
Chris is an Associate Professor at the National University of Singapore and Deputy Director of the NUS institute for the Application of Learning Science and Education Technology. 

**Duration requested**
20 mins

**Comment by ongmin** [comment]
@aelbore Hey Jay, just to confirm, are you still keen to speak on 13th Feb? And could we keep the talk at 20minutes?

**Comment by yongkimleng** [comment]
**Title of your talk**
Snapcache - an opensource Firebase-compatible Realtime-Database

**Talk description**
Snapcache is an opensource implementation of the Firebase Realtime-Database server, which is now part of Google Cloud. Having SDK compatibility with existing public SDKs, Snapcache can be deployed on your own servers and your applications can be redirected there with little modification. Deploy Snapcache backed by redis easily with the template Dockerfiles.

**Team**
Jianrong Wang
James Yong - https://bitbucket.com/yongkimleng
Jerry Tan - https://github.com/thejerrytan

**Presenters & Bio**
Jerry Tan is a full stack developer, who dabbles in everything from sensors to blockchain to deep-learning. He has been actively contributing to the local startup and hackathon scene since he joined NUS’s NOC Silicon Valley programme in 2015.

James is a backend engineer in the valley and also a technical advisor for various startups. Current interests are in computer vision, hardware engineering and distributed systems.
jamesyong.net | roblox.com


**Duration requested**
10 mins

**Comment by aelbore** [comment]
> @aelbore Hey Jay, just to confirm, are you still keen to speak on 13th Feb? And could we keep the talk at 20minutes?

yes, i can make it 20 mins. @ongmin

**Comment by serverwentdown** [comment]
📹 Here are the recorded presentations:

Web Components that works everywhere: https://engineers.sg/v/3210
Snapcache - an opensource Firebase-compatible Realtime-Database: https://engineers.sg/v/3211
From Game-based Learning to Game Creation: https://engineers.sg/v/3212
Modernising a 20 year legacy: https://engineers.sg/v/3213
