### ISSUE TITLE
🎙️ talk.js - June 2020 (online)

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#37]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/271138941/)
- [x] Date: 17 June (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom?

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by cryizzle** [comment]
**Title of your topic**
BreadTalk - Building an intuitive baking tool in VueJS

**Topic description**
I'll be sharing my experience of building a helper tool for baking as a personal project using VueJS

**Presenter(s)**
Crystal Tee (https://github.com/cryizzle)

**Presenter's bio**
I'm an Enterprise Engineer at Facebook and I have ~5years of web development experience as a Full Stack Engineer. Prior to Facebook I have worked in companies specialising in NLP and Video Games, which has exposed me to several languages / frameworks such as ReactJS, VueJS, AngularJS, Spring, Java, PHP and C++. I'm also a baker / pianist / digital artist during my free time!

**Duration**
15-20min sharing + 5min for Q&A

**Deck URL (if any)**
Work in Progress!

**Comment by Weiyuan-Lane** [comment]
**Title of your topic:**
Migrating from Ruby on Rails to a JavaScript SPA.

**Topic description:**
At Viki, it's been a year since we starting migrating from our old RoR application to Next.js . It's a gargantuan task to move a codebase that is 7 - 8 years old, and we're still in the midst of doing that. In this sharing, we would share the pointers on how we started this entire journey (frontend, backend, DevOps), and what we might have done right or wrong.

**Presenter(s):**
Weiyuan Liu (https://github.com/weiyuan-lane)

**Presenter's bio:**
I'm a developer at Rakuten Viki! I also do stuff like volunteering for [GDG Cloud Singapore](https://www.meetup.com/GDG-Cloud-Singapore/) and for Techladies.

I write about random tech stuff on my blog, about frontend things, Cloud technologies, DevOps >.< 

**Duration**
Should be around 15 - 20 minutes

**Deck URL (if any)**
Not yet, but one of the subtopics I have now in writing is [this draft](https://medium.com/@weiyuan.liu/two-ways-to-do-a-b-testing-and-staged-rollouts-with-nginx-3289e88386d2). It's part of how we used Nginx to slowly "strangle" the old RoR application. Other portions will be expanded on separately.

**Comment by akshatamohanty** [comment]
**Title of your topic:**
React-ing fast: How to optimize your components for performance?
 
**Topic description**
React is fast by design. But what happens when it does get slow? How do you write components to extract every inch of performance? In this talk, we will walkthrough the process of diagnosing and optimizing a chat application, to enable it to handle hundreds of messages without lagging. We will learn how to use Chrome Dev Tools and React Dev tools to identify performance bottlenecks. Then, dive deeper into React to under its rendering process. And finally, we'll learn about optimization strategies to make React even faster and more efficient.
 
**Presenter(s)**
Akshata Mohanty
Github: @akshatamohanty
Twitter: [@iamaatoh](https://twitter.com/iamaatoh)
 
**Presenter's bio**
Fullstack Engineer at Rakuten Viki. Architect-turned-software-developer. Night-time AI adventurer and wannabe Muay Thai fighter.
 
**Duration**
15-20min
 
**Deck URL (if any)**
WIP

**Comment by eriknguyen** [comment]
@cryizzle @Weiyuan-Lane @akshatamohanty Thanks all for signing up to share your knowledges in this month's virtual.js :D We'll gather tomorrow at 7PM tomorrow on Zoom, the link will be shared shortly :)
